# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 11:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.TextField()),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('register_limit_date', models.DateField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
