// <auto-generated />
namespace HelmesBootcamp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FKtest18 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FKtest18));
        
        string IMigrationMetadata.Id
        {
            get { return "201703200942216_FKtest18"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
